---
title: R code used to create a table containing ingredients of all products extracted
  from XML dumps of the PSMV
author: Johannes Ranke
date: 2023-11-16
output: html_document
---

```{r}
library(here)
library(dplyr, warn.conflicts = FALSE)
library(xml2)
library(parallel)
library(diffobj)
library(fgpsm)
```

We loop over available zipped xml files, starting from the last published
one.

```{r psmv-xml-ingredients-list, cache = TRUE}
cores = 8
xml_dates <- rev(psmv_xml_dates)[1:length(psmv_xml_dates)]
xml_dates <- rev(psmv_xml_dates)[1:8]
psmv_xml_ingredients_list <- list()
for (xml_date in xml_dates) {
  message("Date: ", xml_date)
  if (is.null(psmv_xml_ingredients_list[[xml_date]])) {
    message("Obtaining ingredients list...")
    psmv_xml_ingredients_list[[xml_date]] <-
      fgpsm:::psmv_xml_get_ingredients(psmv_xml_get(xml_date), cores = cores)
  }
}
object.size(psmv_xml_ingredients_list) |> format(units = "Mb")
```

```{r psmv-xml-ingredients-all}
psmv_xml_ingredients_all <- vctrs::vec_rbind(!!!psmv_xml_ingredients_list,
  .names_to = "date")
```


```{r merge_ingredient_lists}
psmv_xml_product_names |> arrange(cleaned)

wGrps_unique <- sort(unique(psmv_xml_product_names$wGrp))

#options(diffobj.format = "ansi256")


for (wGrp_i in wGrps_unique[1:100]) {
  wGrp_ing_all <- filter(psmv_xml_ingredients_all, wGrp == wGrp_i)
  dates <- sort(unique(wGrp_ing_all$date))
  wNbrs <- sort(unique(wGrp_ing_all$wNbr))
  wGrp_ingredients <- filter(wGrp_ing_all, date == dates[1], wNbr == wNbrs[1]) |>
    select(pk, type, percent, g_per_L)
  for (wNbr_i in wNbrs) {
    for (date_i in dates) {
      wGrp_ingredients_check <- filter(wGrp_ing_all, date == date_i, wNbr == wNbr_i) |>
        select(pk, type, percent, g_per_L)
      if (!identical(wGrp_ingredients, wGrp_ingredients_check)) {
        message("wGrp ", wGrp_i, ", wNbr ", wNbr_i, ", ", date_i, ": Diverging ingredients")
        print(diffPrint(wGrp_ingredients, wGrp_ingredients_check, pager = "off"))
        cat("\n")
      }
    }
  }
  cat("\n")
}
```


Finally, we save the ingredient list to the data directory of the package.

```{r}
```

