---
title: R code used to create tables of descriptions extracted from XML dumps of the PSMV
author: Johannes Ranke
date: 2023-05-04
output: html_document
---

We load the 'here' package to make sure we are writing to the right directory
in the end. Also, we use the 'xml2' and the 'dplyr' packages, and some functions
and data from this package.

```{r}
library(here)
library(dplyr, warn.conflicts = FALSE)
library(xml2)
library(fgpsm)
```

## Application areas

```{r}
last_psmv <- psmv_xml_get()
apparea_nodeset <- xml_find_all(last_psmv, "MetaData[@name='ApplicationArea']/Detail")
apparea_nodeset
node <- apparea_nodeset[[1]]
apparea <- function(node) {
  pk <- xml_attr(node, "primaryKey")  
  # We only look at the code stored in the first Description ("de"), as they
  # are always the same
  code <- xml_attr(xml_child(xml_child(node)), "value") 
  desc <- sapply(xml_children(node), xml_attr, "value")
  ret <- c(pk, code, desc)
  names(ret) <- c("pk", "code", "de", "fr", "it", "en")
  return(ret)
}
psmv_xml_application_areas <- t(sapply(apparea_nodeset, apparea)) |> 
  as_tibble()
print(psmv_xml_application_areas)
```



```{r}
save(
  list = c(
    "psmv_xml_application_areas"
  ),
  file = here("data/psmv_xml_descriptions.rda"),
  compress = "xz")
```

